### ISSUE TITLE
Implement E2E tests: `ScheduleCreateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#114]
### Tasks
 - [x] https://github.com/hiero-ledger/hiero-sdk-java/issues/2447
 - [x] https://github.com/hiero-ledger/hiero-sdk-js/issues/3301
 - [x] https://github.com/hiero-ledger/hiero-sdk-go/issues/1471
 - [ ] Implement `ScheduleCreateTransaction` E2E tests: C++
 - [ ] Implement `ScheduleCreateTransaction` E2E tests: Rust
 - [ ] Implement `ScheduleCreateTransaction` E2E tests: Swift
 - [x] https://github.com/hiero-ledger/hiero-sdk-tck/issues/505
