### ISSUE TITLE
Implement E2E tests: `ScheduleDeleteTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#117]
### Tasks
 - [x] https://github.com/hiero-ledger/hiero-sdk-java/issues/2448
 - [x] https://github.com/hiero-ledger/hiero-sdk-js/issues/3302
 - [ ] https://github.com/hiero-ledger/hiero-sdk-go/issues
 - [ ] Implement `ScheduleDeleteTransaction` E2E tests: C++
 - [ ] Implement `ScheduleDeleteTransaction` E2E tests: Rust
 - [ ] Implement `ScheduleDeleteTransaction` E2E tests: Swift
 - [x] https://github.com/hiero-ledger/hiero-sdk-tck/issues/507
