### ISSUE TITLE
Implement E2E tests: `ScheduleInfoQuery`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#120]
```[tasklist]
### Tasks
 - [ ] Implement `ScheduleInfoQuery` E2E tests: Java
 - [ ] Implement `ScheduleInfoQuery` E2E tests: Javascript
 - [ ] Implement `ScheduleInfoQuery` E2E tests: Go
 - [ ] Implement `ScheduleInfoQuery` E2E tests: C++
 - [ ] Implement `ScheduleInfoQuery` E2E tests: Rust
 - [ ] Implement `ScheduleInfoQuery` E2E tests: Swift
 - [ ] Implement `ScheduleInfoQuery` E2E tests: TCK
```
