### ISSUE TITLE
Implement E2E tests: `ScheduleSignTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#123]
### Tasks
 - [x] https://github.com/hiero-ledger/hiero-sdk-java/issues/2449
 - [x] https://github.com/hiero-ledger/hiero-sdk-js/issues/3303
 - [x] https://github.com/hiero-ledger/hiero-sdk-go/issues/1471
 - [ ] Implement `ScheduleSignTransaction` E2E tests: C++
 - [ ] Implement `ScheduleSignTransaction` E2E tests: Rust
 - [ ] Implement `ScheduleSignTransaction` E2E tests: Swift
 - [x] https://github.com/hiero-ledger/hiero-sdk-tck/issues/508
