### ISSUE TITLE
Implement E2E tests: `SystemUndeleteTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#129]
```[tasklist]
### Tasks
 - [ ] Implement `SystemUndeleteTransaction` E2E tests: Java
 - [ ] Implement `SystemUndeleteTransaction` E2E tests: Javascript
 - [ ] Implement `SystemUndeleteTransaction` E2E tests: Go
 - [ ] Implement `SystemUndeleteTransaction` E2E tests: C++
 - [ ] Implement `SystemUndeleteTransaction` E2E tests: Rust
 - [ ] Implement `SystemUndeleteTransaction` E2E tests: Swift
 - [ ] Implement `SystemUndeleteTransaction` E2E tests: TCK
```
