### ISSUE TITLE
Implement E2E tests: `TokenAssociateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#132]
### Tasks
 - [x] https://github.com/hashgraph/hedera-sdk-java/issues/2161
 - [x] https://github.com/hashgraph/hedera-sdk-js/issues/2726
 - [x] https://github.com/hiero-ledger/hiero-sdk-go/issues/1199
 - [x] https://github.com/hiero-ledger/hiero-sdk-cpp/issues/831
 - [ ] Implement `TokenAssociateTransaction` E2E tests: Rust
 - [x] https://github.com/hiero-ledger/hiero-sdk-swift/issues/379
 - [x] #281
