### ISSUE TITLE
Implement E2E tests: `TokenBurnTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#135]
### Tasks
 - [x] https://github.com/hashgraph/hedera-sdk-java/issues/2161
 - [x] https://github.com/hashgraph/hedera-sdk-js/issues/2726
 - [x] https://github.com/hiero-ledger/hiero-sdk-go/issues/1199
 - [x] https://github.com/hiero-ledger/hiero-sdk-cpp/issues/859
 - [ ] Implement `TokenBurnTransaction` E2E tests: Rust
 - [x] https://github.com/hiero-ledger/hiero-sdk-swift/issues/379
 - [x] #306
