### ISSUE TITLE
Implement E2E tests: `TokenCreateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#138]
### Tasks
 - [x] https://github.com/hashgraph/hedera-sdk-java/issues/2020
 - [x] https://github.com/hashgraph/hedera-sdk-js/issues/2584
 - [x] https://github.com/hiero-ledger/hiero-sdk-go/issues/1133
 - [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/757
 - [ ] Implement `TokenCreateTransaction` E2E tests: Rust
 - [x] https://github.com/hiero-ledger/hiero-sdk-swift/issues/379
 - [x] https://github.com/hashgraph/hedera-sdk-tck/issues/231
