### ISSUE TITLE
Implement E2E tests: `TokenDeleteTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#141]
### Tasks
 - [x] https://github.com/hashgraph/hedera-sdk-java/issues/2089
 - [x] https://github.com/hashgraph/hedera-sdk-js/issues/2585
 - [x] https://github.com/hiero-ledger/hiero-sdk-go/issues/1163
 - [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/789
 - [ ] Implement `TokenDeleteTransaction` E2E tests: Rust
 - [x] https://github.com/hiero-ledger/hiero-sdk-swift/issues/379
 - [x] https://github.com/hashgraph/hedera-sdk-tck/issues/243
