### ISSUE TITLE
Implement JSON-RPC method endpoints for `AccountUpdateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#39]
### Tasks
- [x] https://github.com/hashgraph/hedera-sdk-java/issues/1931
- [x] https://github.com/hashgraph/hedera-sdk-js/issues/2437
- [x] https://github.com/hashgraph/hedera-sdk-go/issues/1018
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/702
- [x] https://github.com/hashgraph/hedera-sdk-rust/issues/839
- [x] https://github.com/hashgraph/hedera-sdk-swift/issues/403
- [x] https://github.com/hashgraph/hedera-sdk-tck/issues/217
