### ISSUE TITLE
Implement E2E tests: `TopicUpdateTransaction`

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#96]
### Tasks
 - [x] https://github.com/hiero-ledger/hiero-sdk-java/issues/2433
 - [x] https://github.com/hiero-ledger/hiero-sdk-js/issues/3240
 - [x] https://github.com/hiero-ledger/hiero-sdk-go/pull/1448
 - [ ] Implement `TopicUpdateTransaction` E2E tests: C++
 - [ ] Implement `TopicUpdateTransaction` E2E tests: Rust
 - [ ] Implement `TopicUpdateTransaction` E2E tests: Swift
 - [x] https://github.com/hiero-ledger/hiero-sdk-tck/issues/471
